### ISSUE TITLE
Type conversion node is not inserted in `if` condition

### ISSUE THREAD

**Issue by vla5924** [vla5924-practice/compiler-project#82]
```py
def main() -> None:
    y: float
    if y > 1: # float > int
        y = 6
    print(y)
```

```
  FunctionDefinition
    FunctionName: main
    FunctionArguments
    FunctionReturnType: NoneType
    BranchRoot: y:FloatType
      VariableDeclaration
        TypeName: FloatType
        VariableName: y
      IfStatement
        Expression
          BinaryOperation: Greater
            VariableName: y
            IntegerLiteralValue: 1
        BranchRoot:
          Expression: FloatType
            BinaryOperation: Assign
              VariableName: y
              TypeConversion
                TypeName: FloatType
                IntegerLiteralValue: 6
```

В elif и while возможно тоже такое поведение, надо проверить
